### ISSUE TITLE
Wrong url path to docs

### ISSUE THREAD

**Issue by partikus** [coduo/unit-of-work#30]
Hi,
in the `README.md` file is given wrong url path to doc.
Wrong: http://docs.isolate-project.org/en/latest/unit-of-work/getting-started/index.html
Proper: http://isolate.readthedocs.org/en/latest/framework/unit-of-work/getting-started/index.html

**Comment by norberttech** [comment]
Actually correct path is http://docs.isolate-project.org/en/latest/framework/unit-of-work/getting-started/index.html but thanks, fixed!
